.SUFFIXES: .cpp .cu .o

LIBS=
LIBDIR=
OBJS=fft_cuda.o complex.o
#NVCCFLAGS= -c -dc
#NVCCFLAGS= -g -c -dc
#NVCC=$(CUDA_PATH)/bin/nvcc

.cpp.o: 
	$(NVCC) -c $(NVCCFLAGS) $(ARCH) $(GENCODE_FLAGS) $<

.cu.o: 
	$(NVCC) -c $(NVCCFLAGS) $(ARCH) $(GENCODE_FLAGS) $<

all: $(OBJS) 

clean: 
		rm -f *~ *.o *.out

wipe: clean
